namespace Apis.Facebook.Enums
{
    public enum UserField
    {
        id,
        about,
        age_range,
        birthday,
        email,
        favorite_athletes,
        favorite_teams,
        first_name,
        gender,
        hometown,
        inspirational_people,
        is_guest_user,
        languages,
        last_name,
        link,
        location,
        meeting_for,
        middle_name,
        name,
        name_format,
        political,
        profile_pic,
        quotes,
        relationship_status,
        religion,
        short_name,
        sports,
        website
    }
}